//By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see //that the 6th prime is 13.

//What is the 10 001st prime number?

//each grouping of primes, the next prime can be found by taking
//in all composite numbers generated by those primes below a limit,
//all gaps are therefore primes. keep track of smallest number before 
//gap, and increment exponent on lesser numbers until it is passed



<?php

?>